# Generated by Django 4.2.8 on 2024-01-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('position', models.PositiveSmallIntegerField(unique=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('slug', models.CharField(db_index=True, max_length=50, unique=True)),
                ('photo', models.ImageField(upload_to='portfolioitem/')),
            ],
        ),
    ]
