# Generated by Django 4.2.8 on 2024-01-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ('position',)},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ('position',)},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ('position',)},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('position',)},
        ),
        migrations.RemoveField(
            model_name='team',
            name='icon',
        ),
        migrations.AddField(
            model_name='team',
            name='facebook_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='team',
            name='instagram_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='team',
            name='twitter_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='photo',
            field=models.ImageField(upload_to='portfolioes/'),
        ),
    ]
