# Generated by Django 4.2.8 on 2024-01-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_partners'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='descr',
            field=models.TextField(default='', max_length=500),
        ),
    ]
